// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Note is a single editable sticky note. Blocks holds BlockNote block JSON.
 */
export interface Note {
    "id": string;

    /**
     * manual title override; empty means derive from first line
     */
    "title": string;
    "blocks": ({ [_ in string]?: any } | null)[] | null;
    "createdAt": number;
    "updatedAt": number;
}

/**
 * Settings holds app-level preferences persisted across restarts.
 */
export interface Settings {
    /**
     * "yellow" | "gray" | "dark"
     */
    "theme": string;
    "alwaysOnTop": boolean;
}
