// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Store is the persistence service bound to the frontend. It owns the data
 * directory (os.UserConfigDir()/slite) and reads/writes notes.json and
 * settings.json. The frontend calls these methods via generated bindings; in
 * pure-browser fallback mode the frontend uses localStorage instead.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * LoadNotes reads all notes from disk. Returns an empty slice if the file does
 * not exist yet.
 */
export function LoadNotes(): $CancellablePromise<$models.Note[] | null> {
    return $Call.ByID(2283733460);
}

/**
 * LoadSettings reads persisted settings (falling back to defaults).
 */
export function LoadSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(4023720530);
}

/**
 * Ping is a trivial binding used to detect whether the frontend is running
 * inside the Wails runtime (native) or in a plain browser (fallback mode).
 * It never fails, unlike LoadNotes/LoadSettings which can error on read.
 */
export function Ping(): $CancellablePromise<string> {
    return $Call.ByID(2107099595);
}

/**
 * SaveNotes persists the full note list atomically.
 */
export function SaveNotes(notes: $models.Note[] | null): $CancellablePromise<void> {
    return $Call.ByID(1083769751, notes);
}

/**
 * SaveSettings persists settings and applies AlwaysOnTop to the window.
 */
export function SaveSettings(settings: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(698043607, settings);
}
