// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MarkdownFile is one note's display name + markdown body, used for bulk
 * .md export.
 */
export interface MarkdownFile {
    "name": string;
    "content": string;
}

/**
 * Note is a single editable sticky note. Blocks holds BlockNote block JSON.
 */
export interface Note {
    "id": string;

    /**
     * manual title override; empty means derive from first line
     */
    "title": string;
    "blocks": ({ [_ in string]?: any } | null)[] | null;
    "createdAt": number;
    "updatedAt": number;
}

/**
 * Settings holds app-level preferences persisted across restarts.
 */
export interface Settings {
    /**
     * "system" | "yellow" | "gray" | "dark"
     */
    "theme": string;
    "alwaysOnTop": boolean;

    /**
     * global toggle accelerator, e.g. "Alt+Shift+S"
     */
    "hotkey": string;

    /**
     * Windows Run key (HKCU)
     */
    "launchAtStartup": boolean;

    /**
     * window opacity 0.3–1.0, 1 = opaque
     */
    "opacity": number;

    /**
     * Window bounds in physical pixels, persisted (debounced) on move/resize
     * so the window reopens where the user left it. 0 = never saved yet.
     * Owned by the Go side (SaveWindowBounds); the frontend must not set them.
     */
    "windowX"?: number;
    "windowY"?: number;
    "windowWidth"?: number;
    "windowHeight"?: number;
}
