// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Store is the persistence service bound to the frontend. It owns the data
 * directory (os.UserConfigDir()/slite by default, configurable) and
 * reads/writes notes.json and settings.json. The frontend calls these methods
 * via generated bindings; in pure-browser fallback mode the frontend uses
 * localStorage instead.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppVersion returns the user-facing version string for the About section.
 */
export function AppVersion(): $CancellablePromise<string> {
    return $Call.ByID(594851662);
}

/**
 * ChooseDataDir opens the native folder picker and returns the selected path,
 * or "" when the user cancels. Error in browser fallback mode.
 */
export function ChooseDataDir(): $CancellablePromise<string> {
    return $Call.ByID(2753525289);
}

/**
 * CurrentDataDir returns the active data directory path (display in settings).
 */
export function CurrentDataDir(): $CancellablePromise<string> {
    return $Call.ByID(55725111);
}

/**
 * LoadNotes reads all notes from disk. Returns an empty slice if the file does
 * not exist yet.
 */
export function LoadNotes(): $CancellablePromise<$models.Note[] | null> {
    return $Call.ByID(2283733460);
}

/**
 * LoadSettings reads persisted settings (falling back to defaults).
 */
export function LoadSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(4023720530);
}

/**
 * OpenDataDir reveals the active data directory in Explorer (no-op in browser
 * fallback mode).
 */
export function OpenDataDir(): $CancellablePromise<void> {
    return $Call.ByID(11373138);
}

/**
 * OpenURL opens a URL in the user's default browser (Windows ShellExecute).
 * Used by the About section's links; WebView2 does not follow external links.
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(547634812, url);
}

/**
 * Ping is a trivial binding used to detect whether the frontend is running
 * inside the Wails runtime (native) or in a plain browser (fallback mode).
 * It never fails, unlike LoadNotes/LoadSettings which can error on read.
 */
export function Ping(): $CancellablePromise<string> {
    return $Call.ByID(2107099595);
}

/**
 * ResumeHotkey restores the toggle hotkey after SuspendHotkey (re-registering
 * whatever combo is current, which may be a newly configured one).
 */
export function ResumeHotkey(): $CancellablePromise<void> {
    return $Call.ByID(2145843646);
}

/**
 * SaveNotes persists the full note list atomically. Note deletion is handled
 * on the frontend (remove from list, then save the full list).
 */
export function SaveNotes(notes: $models.Note[] | null): $CancellablePromise<void> {
    return $Call.ByID(1083769751, notes);
}

/**
 * SaveSettings persists settings and applies window-level side effects
 * (always-on-top, window opacity, auto-start). DataDir is managed
 * exclusively by SetDataDir.
 */
export function SaveSettings(settings: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(698043607, settings);
}

/**
 * SetDataDir validates the target, migrates notes.json (if any), switches the
 * active directory, persists settings, then removes the old slite files.
 */
export function SetDataDir(path: string): $CancellablePromise<void> {
    return $Call.ByID(2189879372, path);
}

/**
 * SetHotkey re-registers the global toggle hotkey (no-op in browser fallback,
 * where hotkeyReconfigure is nil) without persisting; the frontend then calls
 * SaveSettings with the new combo. On any failure the previous binding is left
 * untouched.
 */
export function SetHotkey(combo: string): $CancellablePromise<void> {
    return $Call.ByID(2514178955, combo);
}

/**
 * SetWindowOpacityOverride temporarily forces the window fully opaque while
 * an app-modal overlay (settings panel, theme picker) is open, so the
 * translucent backdrop does not muddy the overlay UI. on=false restores the
 * persisted opacity. No-op in browser fallback (the frontend never calls it).
 */
export function SetWindowOpacityOverride(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(602956902, on);
}

/**
 * SuspendHotkey temporarily unregisters the global toggle hotkey while the
 * user records a new combo in the settings panel, so pressing the old combo
 * mid-recording cannot toggle the window. No-op in browser fallback.
 */
export function SuspendHotkey(): $CancellablePromise<void> {
    return $Call.ByID(3646761851);
}

/**
 * ValidateDataDir runs the pre-migration checks for a candidate data directory.
 * It returns a non-nil error describing the first failed check. Checks:
 *   - resolves to an absolute path
 *   - is not the currently active data directory
 *   - exists and is a directory
 *   - is writable (probe file create+delete)
 *   - contains only slite-owned files (notes.json, settings.json, log.txt) or nothing
 */
export function ValidateDataDir(path: string): $CancellablePromise<void> {
    return $Call.ByID(3489296200, path);
}
