// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Store is the persistence service bound to the frontend. It owns the data
 * directory (os.UserConfigDir()/slite by default, configurable) and
 * reads/writes notes.json and settings.json. The frontend calls these methods
 * via generated bindings; in pure-browser fallback mode the frontend uses
 * localStorage instead.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppVersion returns the user-facing version string for the About section.
 */
export function AppVersion(): $CancellablePromise<string> {
    return $Call.ByID(594851662);
}

/**
 * ChooseDataDir opens the native folder picker and returns the selected path,
 * or "" when the user cancels. Error in browser fallback mode.
 */
export function ChooseDataDir(): $CancellablePromise<string> {
    return $Call.ByID(2753525289);
}

/**
 * CurrentDataDir returns the active data directory path (display in settings).
 */
export function CurrentDataDir(): $CancellablePromise<string> {
    return $Call.ByID(55725111);
}

/**
 * DeleteNote removes a note's file. Removing a missing note is not an error
 * (idempotent, so a stale delete after a reload is harmless).
 */
export function DeleteNote(id: string): $CancellablePromise<void> {
    return $Call.ByID(84314944, id);
}

/**
 * ExportAllMarkdown writes every note as its own .md file into a folder the
 * user picks (defaulting to Downloads). Single-note export passes a
 * one-element slice. Returns the number of files written (0 when the user
 * cancels). Colliding names get a numeric suffix; invalid filename
 * characters are replaced so the export can never fail on the target
 * filesystem.
 */
export function ExportAllMarkdown(files: $models.MarkdownFile[] | null): $CancellablePromise<number> {
    return $Call.ByID(2575122013, files);
}

/**
 * LoadNotes reads all notes from disk (per-note files under notes/), sorting
 * by CreatedAt so the list order is stable regardless of directory order. On
 * the first read after an upgrade it migrates the legacy single-file
 * notes.json into per-note files; a failed migration falls back to serving
 * the legacy data and retries on the next call.
 */
export function LoadNotes(): $CancellablePromise<$models.Note[] | null> {
    return $Call.ByID(2283733460);
}

/**
 * LoadSettings reads persisted settings (falling back to defaults).
 */
export function LoadSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(4023720530);
}

/**
 * MoveDataDir migrates the data (settings.json + notes) into target, points
 * app.json at it, then removes the old files. The target must be empty — this
 * is a move, never an overwrite. Write-then-delete ordering means a crash
 * mid-move leaves the old directory intact and app.json untouched, so no
 * data is lost.
 */
export function MoveDataDir(path: string): $CancellablePromise<void> {
    return $Call.ByID(599783797, path);
}

/**
 * OpenDataDir reveals the active data directory in Explorer (no-op in browser
 * fallback mode).
 */
export function OpenDataDir(): $CancellablePromise<void> {
    return $Call.ByID(11373138);
}

/**
 * OpenMarkdownDialog shows the native open dialog (markdown/text filter) and
 * returns the chosen file's content ("" when the user cancels or the file is
 * empty).
 */
export function OpenMarkdownDialog(): $CancellablePromise<string> {
    return $Call.ByID(3895054086);
}

/**
 * OpenURL opens a URL in the user's default browser (Windows ShellExecute).
 * Used by the About section's links; WebView2 does not follow external links.
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(547634812, url);
}

/**
 * Ping is a trivial binding used to detect whether the frontend is running
 * inside the Wails runtime (native) or in a plain browser (fallback mode).
 * It never fails, unlike LoadNotes/LoadSettings which can error on read.
 */
export function Ping(): $CancellablePromise<string> {
    return $Call.ByID(2107099595);
}

/**
 * ResumeHotkey restores the toggle hotkey after SuspendHotkey (re-registering
 * whatever combo is current, which may be a newly configured one).
 */
export function ResumeHotkey(): $CancellablePromise<void> {
    return $Call.ByID(2145843646);
}

/**
 * SaveNote persists a single note atomically. Per-note files mean editing one
 * note rewrites only that file, never the whole dataset.
 */
export function SaveNote(note: $models.Note): $CancellablePromise<void> {
    return $Call.ByID(882722846, note);
}

/**
 * SaveSettings persists settings and applies window-level side effects
 * (always-on-top, window opacity, auto-start). The data directory is managed
 * exclusively by MoveDataDir/UseDataDir; window bounds exclusively by
 * SaveWindowBounds.
 */
export function SaveSettings(settings: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(698043607, settings);
}

/**
 * SaveWindowBounds persists the window's screen position and size (physical
 * pixels). Called debounced from the Go side on window move/resize; the
 * frontend never calls it. Only the four bounds fields are touched, so the
 * always-on-top / opacity / autostart side effects of SaveSettings do not
 * run on every drag.
 */
export function SaveWindowBounds(x: number, y: number, w: number, h: number): $CancellablePromise<void> {
    return $Call.ByID(2293857695, x, y, w, h);
}

/**
 * SetHotkey re-registers the global toggle hotkey (no-op in browser fallback,
 * where hotkeyReconfigure is nil) without persisting; the frontend then calls
 * SaveSettings with the new combo. On any failure the previous binding is left
 * untouched.
 */
export function SetHotkey(combo: string): $CancellablePromise<void> {
    return $Call.ByID(2514178955, combo);
}

/**
 * SetWindowOpacityOverride temporarily forces the window fully opaque while
 * an app-modal overlay (settings panel, theme picker) is open, so the
 * translucent backdrop does not muddy the overlay UI. on=false restores the
 * persisted opacity. No-op in browser fallback (the frontend never calls it).
 */
export function SetWindowOpacityOverride(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(602956902, on);
}

/**
 * SuspendHotkey temporarily unregisters the global toggle hotkey while the
 * user records a new combo in the settings panel, so pressing the old combo
 * mid-recording cannot toggle the window. No-op in browser fallback.
 */
export function SuspendHotkey(): $CancellablePromise<void> {
    return $Call.ByID(3646761851);
}

/**
 * UseDataDir adopts an existing slite data directory (or an empty folder as a
 * fresh one) without copying or deleting anything: app.json points at it and
 * preferences reload from it. This is how a reinstall / new machine reconnects
 * to previously created data.
 */
export function UseDataDir(path: string): $CancellablePromise<void> {
    return $Call.ByID(2877999749, path);
}

/**
 * ValidateDataDir runs the pre-checks for a candidate data directory in
 * "adopt" mode (empty, or containing only slite-owned files). The settings
 * panel calls it for a fast failure before the real operation.
 */
export function ValidateDataDir(path: string): $CancellablePromise<void> {
    return $Call.ByID(3489296200, path);
}
